# Generated by Django 3.1 on 2020-08-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200820_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='teacher_id',
            new_name='lecturer_id',
        ),
    ]
