# Generated by Django 3.1 on 2020-08-20 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200820_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='datetime',
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='total_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.category'),
        ),
    ]
