# Generated by Django 3.1 on 2020-08-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200820_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'CATEGORIES'},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'verbose_name_plural': 'LECTURERS'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'STUDENTS'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'SUBJECTS'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name_plural': 'TIMES TABLE'},
        ),
    ]
