# Generated by Django 3.1 on 2020-08-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200820_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name_plural': 'TIME TABLE'},
        ),
    ]
